site_name: USTC 编译原理和技术(H) 2025
repo_name: ustc-compiler/2025
repo_url: https://github.com/ustc-compiler/2025
theme:
  name: 'material'
  palette:
    primary: 'black'
  language: 'zh'
  features:
    - content.code.copy
    - navigation.tabs
markdown_extensions:
  - mdx_spanner # see https://pypi.org/project/mdx-spanner/
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - mdx_truly_sane_lists
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - css/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
nav:
  - 首页: README.md
  - 课程安排: schedule.md
  - 公共文档:
    - C++ 介绍: common/simple_cpp.md
    # - Logging 工具使用: common/logging.md
    - IDE 配置: common/ide.md
    - 平台介绍:
      - 头歌平台: common/educoder.md
  # - Lab0:
  #   - Lab0 简介: lab0/index.md
  #   - Linux 环境配置: lab0/linux.md
  #   - LLVM 等软件环境配置: lab0/software.md
  #   - Git 的使用: lab0/git.md
  - 拓展阅读:
    - 从词法分析到LLM Tokenizer: further/tokenizer.md
    - 其他: further/further.md
